### ISSUE TITLE
Everybody is able to work on their own (toolchain setup)

### ISSUE THREAD

**Issue by Pepperrs** [ise-ethereum/on-chain-chess#10]
# Story 

## User story

As a developer, I want to be able to work on the tasks that are assigned to me. I also need to be able to review code that other developers wrote.

## Tasks
- #11 Introduction to waffle.io
- #12 Introduction to Jenkins
- #13 Introduction to new JS features and Webpack
- #14 Introduction to 0x88 chess
- #15 Introduction to solidity
- #16 Setup services and environments
- #5 Decide upon web framework
- #8 Choose Ethereum development tools/libraries

## Acceptance criteria

- [x] Every developer has a working development environment
- [x] Every developer understands the structure of the project
- [x] Every developer knows about and is able to use the toolchain
- [x] Backend developers are able to deploy and test contracts
- [x] Frontend developers are able to deploy frontend resources, like static content

## Notes

- Deployment possibility for the frontend team depends that the server has been set up (#46)
