### ISSUE TITLE
P2P-Proxy: Back-End-Proxy

### ISSUE THREAD

**Issue by lisasi** [ise-ethereum/on-chain-chess#118]
# Task
## Detailed Description

- Build a p2p proxy that allows for communication between different players
## Associated story

Story: #117 Play off-chain-chess without validation
## Notes

- [x] Connect
- [x] Send to address / topic
- [x] Listen on own address
- [x] Listen for topic

**Comment by graup** [comment]
Implemented in https://github.com/ise-ethereum/insecure-ethereum-p2p-proxy
