### ISSUE TITLE
Validate move/new state and send ACK

### ISSUE THREAD

**Issue by lisasi** [ise-ethereum/on-chain-chess#124]
# Task
## Detailed Description

- Validate moves that are received via the proxy
- acknowledge moves received.
## Associated story

Story: #122  Validate and acknowledge received moves
## Notes

- [x] Factory function to listen for moves and validate them
- [x] in playGame, call listener with callback that updates the game state #121 
- [x] ACK new state `games.sendAck(game)`

```
...
games.listenForMoves(game, function(m) {
  let [msgType, state, stateSignature, fromIndex, toIndex, moveSignature] = m.payload;
  // Does not need to validate here, is already validated!
  // Do something with state, fromIndex, toIndex
  ...
});
...
```

**Comment by graup** [comment]
https://github.com/ise-ethereum/on-chain-chess/commits/feature/shh
