### ISSUE TITLE
Claim checkmate, stalemate and surrender and submit to BC/claim ether

### ISSUE THREAD

**Issue by lisasi** [ise-ethereum/on-chain-chess#127]
# Story
## User story

As a user, I want the game to end on stale/checkmate, and I want to be able to surrender. If any of this happens i want to be able to claim any won ether. 
## Tasks
#128 Find out how to validate signatures in BC
#129 Function to accept current state + next move in BC
#130 Claim win etc. (Test)
#131 Submit from Frontend
#166 Add states and moves to local storage
## Acceptance criteria

- [ ]  Front ends can communicate without using the contract.
- [ ]  The winner can prove to the contract that they have won, even if the contract has never received any of the moves .
- [ ] Draws lead to the game being a draw and a player can not use claimTimeout to defeat a player who is in stalemate.
