### ISSUE TITLE
Create diagrams

### ISSUE THREAD

**Issue by Tin-App** [ise-ethereum/on-chain-chess#145]
# Task
## Detailed Description

Create diagrams that show 
- [x] turn logic 
  https://github.com/ise-ethereum/on-chain-chess/wiki/Chess%20turn%20logic
- [ ] contract class structur
- [ ] overview how BC / Gui  /Nodes /contracts work with each other
- [ ] endgame challenge/response @graup
## Associated story

Story: #157
