### ISSUE TITLE
The user can initialize a game of chess

### ISSUE THREAD

**Issue by Pepperrs** [ise-ethereum/on-chain-chess#18]
# Story 

## User story

As a user, I want to be able to start a new game of chess and choose my starting color. I need to know the game ID so that I can tell others to join the game.

## Tasks
- #6 Create a basic website template
- #26 Create an HTML page to start a new game
- #46 Set up a server for static resources
- #44 Create backend method to initialize a game

## Acceptance criteria

- [x] When starting a game, the user has to enter his name
- [x] The user chooses a color (black or white)
- [x] After the game was initialized the user can view the gameID
