### ISSUE TITLE
User is able to reenter a joined game after crash/reload

### ISSUE THREAD

**Issue by graup** [ise-ethereum/on-chain-chess#39]
# Story

## User story

As a user, I want to reenter a game if i have lost connection.

## Tasks
- #79 Get game state from contract
- #80 Implement gamesOfPlayers getter function
- #81 FrontEnd fetches and displays the current state of the game

## Acceptance criteria

- [ ] The client remembers the game
- [ ] The user can only open a game he was already part of
- [ ] The client renders the game when the user opens it
- [ ] The user can reconnect to a game where there is one or no player left in the game
- [ ] The user can reconnect to a game only if the game had been started but not ended yet
