### ISSUE TITLE
Implement end game conditions

### ISSUE THREAD

**Issue by Pepperrs** [ise-ethereum/on-chain-chess#53]
# Story

## User story

As a user, I want to be able to win or tie or loose a game and be notified about it.

## Tasks
- Implement an "End game" / Surrender button #42
- Display if a player has won/tied/lost a game according to the board #60
- Client determines if the game has reached an end #61
- Backend verifies check mate #49
- Backend verifies stale mate #73

## Acceptance criteria

- [ ]  You can surrender and will subsequently looses the game 
- [ ]  Checkmate wins the game
- [ ]  Remis is a remis
- [ ]  The participants are notified of their win or loss
- [ ] There are tests for verifying checkmate and stalemate

**Comment by graup** [comment]
Should we add the 50 move rule? If I understood it correctly, we need another counter that counts moves since the last capture. If it exceeds 100, the game is drawn. [Source](http://www.chessvariants.com/d.chess/50moves.html)

**Comment by kyroy** [comment]
Would be more efficient to store the move, where last capture took place.
