### ISSUE TITLE
Play for ether

### ISSUE THREAD

**Issue by Pepperrs** [ise-ethereum/on-chain-chess#71]
# Story

## User story

As a user i want to play for my hard earned ether and be able to win ether if I win

## Tasks
- #87 Initialize game frontend
- #88 Join game frontend
- #89 Create / join game backend
- #90 Game bet information backend
- #91 Transfer won ether backend
- #92 Display won ether

## Acceptance criteria

- [ ] The winner gets the ether of both participants
- [ ] The the looser gets nothing
- [ ] The contract is paid the ether at the beginning of the game and pays it towards the winner

**Comment by kyroy** [comment]
https://blog.ethereum.org/2016/06/10/smart-contract-security/
