### ISSUE TITLE
Players can agree to draw a game

### ISSUE THREAD

**Issue by dennis-westphal** [ise-ethereum/on-chain-chess#93]
# Story
## User story

The users are able to aggree on drawing a game.
## Tasks
- #140 Add contract draw functions & events
- #141 Frontend features to draw a game
- #168 Player can offer draw
- #169 As a player, I want to see any timeouts that are running against me 
## Acceptance criteria

- [ ] Any player can suggest a draw if it is his turn
- [ ] The other player is informed about the wish for a draw
- [x] He can then accept or reject the wish for a draw
- [x] His decision is shown to the first player
- [x] If the game is drawn, the ether is transferred back to both players (after the frontend requested it)
## Notes

By implementing this method, we can neglect all the special rules that would also result in a draw.
